# Generated by Django 5.1.1 on 2024-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0003_alter_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, default='user', related_name='roles_employees', to='webview.role'),
        ),
    ]
